# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Blog
tagline:          'developer's blog'
description:      'Follow me <a href="https://twitter.com/vedarthk" target="_blank">@vedarthk</a>.'
url:              http://blog.vedarthz.in

author:
  name:           'Vedarth Kulkarni'
  url:            https://twitter.com/vedarthk

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/vedarthk/hyde